### ISSUE TITLE
Not working on safari mobile.

### ISSUE THREAD

**Issue by Pupix** [jsilvermist/fullscreen-api#1]
Hey,
I don't know if you still support this or not but I am gonna write this issue anyway.

Safari mobile on iOS 10ish doesn't have any of the fullscreen APIs and your module throw instead of doing nothing.

The problem can be seen here: https://github.com/jsilvermist/fullscreen-api/blob/02e94c757bebe1934f2acf2f7af0fac5b0324dce/fullscreen-api.js#L56

If `api` is null, because it couldn't be found in any of the provided vendors, it throws an error.

**Comment by jsilvermist** [comment]
Gotcha, I'll try to push out a fix ASAP, just might not have time to work on this today.

Thanks for pointing this out.

**Comment by jsilvermist** [comment]
Fixed by https://github.com/jsilvermist/fullscreen-api/commit/8f588c39aa6699329da23aaea8c950ea37942a89 and published as [0.2.1](https://www.npmjs.com/package/@jsilvermist/fullscreen-api/v/0.2.1).

PS: I'm half asleep, so LMK if I missed anything. 😉 💤
